# Site configuration
repository: sproogen/resume-theme
favicon: images/favicon.ico
remote_theme: sproogen/resume-theme

# Content configuration version
version: 2

# Personal info
name: Mohammed Tasdir Ahmmed
title: Cyber Security Analyst
website: www.tasdirahmmed.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: tasdir_x
github_username: tasdir
linkedin_username: tasdir

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# Blog settings
blog:
  title: "My Blog"
  description: "Insights, tips, and updates from the world of cyber security."
  categories_enabled: true
  tags_enabled: true

# Navigation
navigation:
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Categories
    url: /categories/
  - title: Tags
    url: /tags/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed
