# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohammed Tasdir Ahmmed
title: Cyber Security Analyst
website: www.tasdirahmmed.com


# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: tasdir_x
github_username: tasdir
linkedin_username: tasdir

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I am Mohammed Tasdir Ahmmed. With over five years of experience as a Cyber Security Researcher, I have conducted vulnerability assessments, penetration testing, and malware analysis. My work has contributed to the security of over 50 organizations including notable names like Cambridge University and Microsoft.
  
  I have also represented Bangladesh at various international platforms, reflecting my dedication to the field of cyber security.

# Experience
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: ABC
        link: abc.com
        sub_title: Cyber Security Analyst
        caption: February 2022 - Present
        quote: >
          Lead critical security assessments and delivered training on malware analysis and threat hunting.
        description: |
          At Fusion IT, my role involves conducting comprehensive malware analysis and vulnerability assessments, ensuring robust security practices across the company's infrastructure. I also provide quarterly security reports and lead training sessions for the team.

      - layout: left
        title: XYZ
        link: xyz.com
        sub_title: Chief Executive Officer
        caption: January 2023 - Present
        quote: >
          Pioneering a crowdsourced global penetration testing platform.
        description: |
          As CEO of Disclosify, I oversee the development of our core product and organize national cyber security competitions and conferences, driving innovation and leadership in the cyber security domain.

# Education
  - title: Education
    layout: list
    content:
      - layout: left
        title: Independent University, Bangladesh
        caption: 2018
        sub_title: BSc Computer Science and Engineering
        description: |
          Pursuing a Bachelor's degree in Computer Science and Engineering, where I am gaining advanced knowledge in cyber security, network systems, and software development.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
